server:
  port: 8080
spring:
  datasource:
    url: dummy
    username: dummy
    password: dummy
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml